# Generated by Django 4.2.4 on 2023-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
