# Generated by Django 4.2.5 on 2023-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_card_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
