# Generated by Django 4.2.4 on 2023-09-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_collection_card_alter_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='card',
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, to='core.card'),
        ),
    ]
