# Generated by Django 4.2.4 on 2023-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card_artist_card_hp_card_large_image_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(blank=True, to='core.card'),
        ),
    ]
